#!/bin/bash
echo `date +%s`>>$4.log
NOW=$(date +"%Y%m%d_%H%M%S")
LOGFILE="usrp_driver_$2__$NOW.log"

#./usrp_driver "$@" > ../log/$LOGFILE  2>&1
echo `pwd`
/home/radar/usrp/usrp_driver/usrp_driver "$@" > ../log/$LOGFILE  2>&1

