#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
Generates network config file for all interaces...
Created on Wed Sep  7 18:14:36 2016

@author: mguski
"""


import socket
import string


PORTS_PER_CARD = 4
configFileName = '/etc/network/interfaces.d/interfaces10G_usrp.cfg'

hostName = socket.gethostname()
print(hostName)
if hostName == 'kodiak-aux':
   interface_bases = ['ens4f', 'ens6f', 'ens2f']
   SUBNET_BASE = 48
elif hostName == 'kodiak-main':
   interface_bases = ['enp10s0f', 'enp11s0f']
   SUBNET_BASE = 40
elif hostName == 'superdarn-lab':
   interface_bases = ['ens85f','ens93f','ens118f']
   SUBNET_BASE = 41
else:
   print('error: unkown host name: ' + hostName)
   quit()
   # interface_bases = ['enp4s0f', 'enp9s0f', 'enp10s0f', 'enp11s0f']
print("generatin {} for {}: \n\n ".format(configFileName, hostName))

ifcfg_template = '''
auto $NETWORKINTERFACE
iface $NETWORKINTERFACE inet static
  address 192.168.$SUBNET.1
  netmask 255.255.255.0
  mtu 9000

'''
cfgText = '# Config for USRP interfaces\n# auto-generated by ' + __file__  + '\n'

interfaces = [ibase + str(p) for ibase in interface_bases for p in range(PORTS_PER_CARD)]


for i, interface in enumerate(interfaces):
   subnet = i + SUBNET_BASE
   currentCFG = string.Template(ifcfg_template)
   currentCFG = currentCFG.substitute(\
                                       SUBNET = subnet,\
                                       NETWORKINTERFACE = interface)
                          
   cfgText += currentCFG
                 

print(cfgText)
f = open(configFileName, 'w+')
f.write(cfgText)
f.close()
